<div class="jumbotron">
    <h1>Welcome to Zend Framework 2</h1>
    <p>Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.</p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank">Fork Zend Framework 2 on GitHub &raquo;</a></p>
</div>